# Change these first
owner: winnin # Your GitHub organization or username, where this repository lives
repo: winnin.github.io # The name of this repository

sites:
  - name: Winnin
    url: https://winnin.com
  - name: Winnin Insights
    url: https://insights.winnin.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.winnin.com
  # baseUrl: /your-repo-name
  logoUrl: https://assets.website-files.com/600f14d617ea3d4f40ecfa21/600f14d617ea3d4769ecfc47_Logo%2520Winnin_Horizontal%2520Black-p-500.png
  icon: https://insights.winnin.com/static/media/favicon.8204afb1.png
  name: Winnin
  introTitle: "**Winnin** uptime monitor and status page."
  introMessage: ""
  navbar:
    - title: Winnin
      href: https://winnin.com
    - title: Insights
      href: https://insights.winnin.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
